export const SEX = {
  male: 'male',
  female: 'female',
};

export const mobDefinitions = [
  {title: "", descript: "elf girl", sex: SEX.female },
  {title: "", descript: "box face", sex: SEX.male },
  {title: "", descript: "chaotic hair", sex: SEX.male },
  {title: "", descript: "bold face", sex: SEX.male },
  {title: "", descript: "fat face", sex: SEX.male },
  {title: "", descript: "charming knight", sex: SEX.male },
  {title: "", descript: "elf merchant", sex: SEX.male },
  {title: "", descript: "cow one", sex: SEX.female },
  {title: "", descript: "elf bard", sex: SEX.male },
  {title: "", descript: "elf girl with dark hair", sex: SEX.female },
  {title: "", descript: "young troll", sex: SEX.male },
  {title: "", descript: "horned inspector", sex: SEX.male },
  {title: "", descript: "citizen", sex: SEX.male },
  {title: "", descript: "blond hair", sex: SEX.female },
  {title: "", descript: "pig one", sex: SEX.male },
  {title: "", descript: "sqared orc", sex: SEX.male },
  {title: "", descript: "bar tender ogre", sex: SEX.male },
  {title: "", descript: "wizard", sex: SEX.male },
  {title: "", descript: "handsome human", sex: SEX.male },
  {title: "", descript: "neighbour", sex: SEX.male },
  {title: "", descript: "long hair", sex: SEX.male },
  {title: "", descript: "six horn", sex: SEX.male },
  {title: "", descript: "desert warrior", sex: SEX.male },
  {title: "", descript: "sad fighter", sex: SEX.male },
  {title: "", descript: "trader", sex: SEX.male },
  {title: "", descript: "paladin", sex: SEX.male },
  {title: "", descript: "knight girl", sex: SEX.female },
  {title: "", descript: "adventurer", sex: SEX.male },
  {title: "", descript: "psycho", sex: SEX.male },
];

export const itemDefinitions = [
  {title: "", descript: "saw knife"},
  {title: "", descript: "short sword"},
  {title: "", descript: "halberd"},
  {title: "", descript: "bow"},
  {title: "", descript: "iron shield"},
  {title: "", descript: "rounded shield"},
  {title: "", descript: "sword"},
  {title: "", descript: "dagger"},
  {title: "", descript: "spiked jerk"},
  {title: "", descript: "staff"},
  {title: "", descript: "bishop staff"},
  {title: "", descript: "axe"},
  {title: "", descript: "ring"},
  {title: "", descript: "bold blade"},
  {title: "", descript: "rapier"},
  {title: "", descript: "hammer"},
  {title: "", descript: "recoil bow"},
  {title: "", descript: "xiphos"},
  {title: "", descript: "harpoon"},
  {title: "", descript: "spear"},
  {title: "", descript: "great shield"},
  {title: "", descript: "knife"},
  {title: "", descript: "mallet"},
  {title: "", descript: "long sword"},
  {title: "", descript: "dual axe"},
  {title: "", descript: "sabre"},
  {title: "", descript: "knight sword"},
  {title: "", descript: "crossbow"},
  {title: "", descript: "claw"},
  {title: "", descript: "broad sword"},
  {title: "", descript: "barbarian axe"},
  {title: "", descript: "saw dagger"},
  {title: "", descript: "cup"},
  {title: "", descript: "material"},
  {title: "", descript: "chest"},
  {title: "", descript: "bag"},
  {title: "", descript: "coin"},
  {title: "", descript: "anvil"},
  {title: "", descript: "box"},
  {title: "", descript: "potion"},
  {title: "", descript: "stone"},
  {title: "", descript: "chicken"},
  {title: "", descript: "goblet"},
  {title: "", descript: "flag"},
  {title: "", descript: "point of interest"},
];